# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YogaFinal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SDWebImage'
pod 'youtube-ios-player-helper'
  # Pods for YogaFinal

end
